//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov052/daObjEmmLog_c  (7 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021111a0  src/_ZN13daObjEmmLog_cD1Ev.cpp
 *   [1] 0x021111e4  src/_ZN13daObjEmmLog_cD0Ev.cpp
 *   [2] 0x0211123c  src/_ZN13daObjEmmLog_c16CleanupResourcesEv.cpp
 *   [3] 0x02111284  src/_ZN13daObjEmmLog_c6RenderEv.cpp
 *   [4] 0x021112ac  src/_ZN13daObjEmmLog_c8BehaviorEv.cpp
 *   [5] 0x02111348  src/_ZN13daObjEmmLog_c13InitResourcesEv.cpp
 *   [6] 0x02111410  src/daObjEmmLog_c_Spawn.c
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjEmmLog_c.h"
#include "SharedFilePtr.h"   /* CleanupResources releases the two shared files by name */

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0xd4]; Base base; };

/* shadow struct 'daObjEmmLog_c_Resources' */
struct daObjEmmLog_c_Resources {
    SharedFilePtr *model;
    SharedFilePtr *collision;
    CLPS_Block *clps;
};

extern "C" {
void func_020393a4(int *clsn, int v);
/* The name claims Fix12<int> by value; the bytes take a plain word, the same
disagreement include/dBgActor_c.h records for both IsClsnInRange symbols. */
int _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void *self, int range, int b);
extern short data_02082214[];
extern daObjEmmLog_c_Resources data_ov052_021124d4;
extern "C" void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block( dBgW_KcMbg *, KCL_File *, const Matrix4x3 *, Fix12i, s16, CLPS_Block *);
extern void *_ZN7fBase_cnwEj(unsigned);
extern void _ZN10dBgActor_cC2Ev(void *);
extern int _ZTV13daObjEmmLog_c[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- daObjEmmLog_c_Spawn, 0x02111410, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol daObjEmmLog_c_Spawn
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *daObjEmmLog_c_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(808);
    if (p) { _ZN10dBgActor_cC2Ev(p); p[0] = (int)&_ZTV13daObjEmmLog_c[2]; }
    return p;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN13daObjEmmLog_c13InitResourcesEv, 0x02111348, size 0xc8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_c13InitResourcesEv
/* 2004/b56 homes the real Fix12<int>-by-value member form through a literal
 * pool instead of passing the immediate found in the ROM. Keep this one ABI
 * seam until the shared fixed-point compiler wall is solved. */
int daObjEmmLog_c::InitResources()
{
    mModel.SetFile((BMD_File *)Model::LoadFile(*data_ov052_021124d4.model), 1, -1);
    UpdateModelPosAndRotY();
    UpdateClsnPosAndRot();

    _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
        &mMeshCollider,
        (KCL_File *)dBgW_Kc::LoadFile(*data_ov052_021124d4.collision),
        &mClsnMat, 0x1000, mAngleY, data_ov052_021124d4.clps);

    mBasePosY = mPosY;
    u8 amplitude = param1 & 0xff;
    if (amplitude == 0xff || param1 == 0)
        mBobAmplitude = 0x64000;
    else
        mBobAmplitude = amplitude * 0xa000;

    mSpinAngle = mAngleX;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN13daObjEmmLog_c8BehaviorEv, 0x021112ac, size 0x9c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_c8BehaviorEv
/* daObjEmmLog_c::Behavior -- vtable slot 6. The rolling log of Tiny-Huge
 * Island: it spins at a fixed rate and rides up and down on a sine of its own
 * spin angle, mBobAmplitude being the amplitude and mBasePosY the centre height. */
int daObjEmmLog_c::Behavior()
{
    func_020393a4((int *)&mMeshCollider, 0x600000);

    int idx = (u16)mSpinAngle >> 4;
    int s = *(short *)((char *)data_02082214 + (idx << 2));
    int m = (int)(((long long)mBobAmplitude * s + 0x800) >> 12);
    mPosY = mBasePosY + m;

    mSpinAngle += 0x200;

    UpdateModelPosAndRotY();
    UpdateClsnPosAndRot();
    _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(this, 0x600000, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN13daObjEmmLog_c6RenderEv, 0x02111284, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_c6RenderEv
/* daObjEmmLog_c::Render - name recovered from the vtable slot it fills.
   The body is a decompilation verified against the ROM, not an
   inferred stub. Real C++ method over the shared header; the Model
   sub-object at +0xd4 is rendered through its own vtable. */
int daObjEmmLog_c::Render() { Base *b = &((Derived *)this)->base; b->m(0); return 1; }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN13daObjEmmLog_c16CleanupResourcesEv, 0x0211123c, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_c16CleanupResourcesEv
/* daObjEmmLog_c::CleanupResources -- vtable slot 3. Takes the inherited mesh
 * collider out of the collision world if it is still in it, then releases the
 * two shared files the log holds. */
int daObjEmmLog_c::CleanupResources()
{
    if (mMeshCollider.IsEnabled()) {
        mMeshCollider.Disable();
    }
    data_ov052_021124d4.model->Release();
    data_ov052_021124d4.collision->Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN13daObjEmmLog_cD0Ev, 0x021111e4, size 0x58 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_cD0Ev
/* recovered: real C++ deleting destructor -- the compiler emits the whole body
 *
 * D0 is the DELETING destructor: destroy through this class and its bases,
 * then return the object to its heap. Declaring `~daObjEmmLog_c()` is enough;
 * mwcc emits D2, D0 and D1 together and objisolate keeps the one this file is
 * bound to. The deallocation is an inline operator delete, matching
 * BigBrickBlock's D0 (include/BigBrickBlock.h, src/_ZN13BigBrickBlockD0Ev.cpp).
 */
/* (no definition here: one `~daObjEmmLog_c()` definition emits the whole
 * D2/D1/D0 group, and it is written at the bottom of this file with D1, the
 * lowest-addressed of the three.) */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN13daObjEmmLog_cD1Ev, 0x021111a0, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjEmmLog_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 *
 * Two vtable stores and three destructor calls, every one a consequence of
 * `struct daObjEmmLog_c : dBgActor_c`: its own vptr, then dBgActor_c's --
 * inlined, because dBgActor_c's destructor is defined in its class body --
 * then dBgActor_c's Model and dBgW_KcMbg, then dActor_c. This class
 * adds no member with a destructor of its own (mBasePosY/mBobAmplitude are plain
 * s32).
 */
/* (no definition here: `virtual ~daObjEmmLog_c() {}` is in
 * include/daObjEmmLog_c.h. One definition emits the whole D2/D1/D0 group, and
 * only the in-class spelling emits it in ROM-ascending order -- see the comment
 * on that declaration.) */
