//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov033/daObjTtFuta_c  (7 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021111a0  src/_ZN13daObjTtFuta_cD1Ev.cpp
 *   [1] 0x021111e4  src/_ZN13daObjTtFuta_cD0Ev.cpp
 *   [2] 0x0211123c  src/_ZN13daObjTtFuta_c15OnGroundPoundedER8dActor_c.cpp
 *   [3] 0x02111280  src/_ZN13daObjTtFuta_c16CleanupResourcesEv.cpp
 *   [4] 0x021112c4  src/_ZN13daObjTtFuta_c6RenderEv.cpp
 *   [5] 0x021112ec  src/_ZN13daObjTtFuta_c8BehaviorEv.cpp
 *   [6] 0x02111310  src/_ZN13daObjTtFuta_c13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjTtFuta_c.h"
#include "decl_common.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0xd4]; Base base; };

extern "C" {
extern void _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(unsigned int a, int x, int y, int z);
extern void _ZN5Sound9PlayBank3EjRK7Vector3(unsigned int a, void *v);
extern void _ZN5Event6SetBitEj(unsigned int b);
extern void _ZN13SharedFilePtr7ReleaseEv(void *);
extern int data_ov033_021124c8[];
extern "C" int _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void *self, int a, int b);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN13daObjTtFuta_c13InitResourcesEv, 0x02111310, size 0x94 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_c13InitResourcesEv
#include "daObjTtFuta_c.h"
// recovered name: daObjTtFuta_c_InitResources
/* recovered: renamed to Class_Method, declarations from a shared header */
#include "decl_common.h"
/* recovered: renamed to Class_Method */
/* daObjTtFuta_c::InitResources - recovered from vtable slot identity */
extern "C" {
extern void* _ZN5Model8LoadFileER13SharedFilePtr(void*);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void*, void*, int, int);
extern void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void*);
extern void _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void*);
extern void* _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(void*);
extern void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(void*, void*, void*, int, short, void*);
extern int _ZN5Event6GetBitEj(unsigned int);
extern int data_ov033_02111bfc[];
s32 daObjTtFuta_c::InitResources() {
    char * c = (char *)this;
  void *f = _ZN5Model8LoadFileER13SharedFilePtr((void*)data_ov033_021124c8);
  _ZN9ModelBase7SetFileEP8BMD_Fileii(c+0xd4, f, 1, -1);
  _ZN10dBgActor_c21UpdateModelPosAndRotYEv(c);
  _ZN10dBgActor_c19UpdateClsnPosAndRotEv(c);
  void *k = _ZN7dBgW_Kc8LoadFileER13SharedFilePtr((void*)data_ov033_021124c0);
  _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(c+0x124, k, c+0x2ec, 0x199, *(short*)(c+0x8e), data_ov033_02111bfc);
  return _ZN5Event6GetBitEj(0xe) == 0;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN13daObjTtFuta_c8BehaviorEv, 0x021112ec, size 0x24 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_c8BehaviorEv
// recovered name: daObjTtFuta_c_Behavior
/* recovered: renamed to Class_Method */
/* daObjTtFuta_c::Behavior - recovered from vtable slot identity */
s32 daObjTtFuta_c::Behavior() {
    void * c = (void *)this;
    _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(c, 0, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN13daObjTtFuta_c6RenderEv, 0x021112c4, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_c6RenderEv
// recovered name: daObjTtFuta_c_Render
/* recovered: renamed to Class_Method */
/* daObjTtFuta_c::Render - recovered from vtable slot identity */
s32 daObjTtFuta_c::Render() {
    Derived * d = (Derived *)this; Base *b = &d->base; b->m(0); return 1; }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN13daObjTtFuta_c16CleanupResourcesEv, 0x02111280, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_c16CleanupResourcesEv
// recovered name: daObjTtFuta_c_CleanupResources
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* daObjTtFuta_c::CleanupResources - recovered from vtable slot identity */
s32 daObjTtFuta_c::CleanupResources() {
    void * t = (void *)this;
    if (_ZN4dBgW9IsEnabledEv((char *)t + 0x124)) {
        _ZN4dBgW7DisableEv((char *)t + 0x124);
    }
    _ZN13SharedFilePtr7ReleaseEv(data_ov033_021124c8);
    _ZN13SharedFilePtr7ReleaseEv(data_ov033_021124c0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN13daObjTtFuta_c15OnGroundPoundedER8dActor_c, 0x0211123c, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_c15OnGroundPoundedER8dActor_c
/* daObjTtFuta_c::OnGroundPounded -- vtable slot 21, ov033 0x0211123c.
 *
 * Real member function: fBase_c::MarkForDestruction is a real method
 * (include/fBase_c.h), and &mCamSpacePosX (a real named field,
 * include/dActor_c.h) replaces `this + 0x74` as the Vector3 argument.
 * `other`'s own position (mPosX/mPosY/mPosZ) stays a raw pointer read
 * (`(char *)&other + 0x5c`, then `v[0..2]`) rather than three named-field
 * reads: the ROM computes one base address and offsets from it (`add r3,
 * r1, #0x5c` then three `ldr [r3, #N]`), not three independent field
 * loads -- member-access syntax compiled to the latter and cost 4 words. */
void daObjTtFuta_c::OnGroundPounded(dActor_c &other)
{
    int *v = (int *)(((char *)&other) + 0x5c);
    _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(0x28, v[0], v[1], v[2]);
    _ZN5Sound9PlayBank3EjRK7Vector3(0xf, &mCamSpacePosX);
    _ZN5Event6SetBitEj(0xe);
    MarkForDestruction();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN13daObjTtFuta_cD1Ev, 0x021111a0, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjTtFuta_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body.
 * Vtable slot 16: one vtable store, the members in reverse, then ~dBgActor_c. */
daObjTtFuta_c::~daObjTtFuta_c()
{
}
