//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov002/daWarpkun_c  (8 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x020ec388  src/_ZN11daWarpkun_cD1Ev.cpp
 *   [1] 0x020ec3b8  src/_ZN11daWarpkun_cD0Ev.c
 *   [2] 0x020ec3fc  src/_ZN11daWarpkun_c16CleanupResourcesEv.cpp
 *   [3] 0x020ec404  src/_ZN11daWarpkun_c16OnPendingDestroyEv.cpp
 *   [4] 0x020ec408  src/_ZN11daWarpkun_c6RenderEv.cpp
 *   [5] 0x020ec410  src/_ZN11daWarpkun_c8BehaviorEv.cpp
 *   [6] 0x020ec4c4  src/_ZN11daWarpkun_c13InitResourcesEv.cpp
 *   [7] 0x020ec534  src/daWarpkun_c_Spawn.c
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daWarpkun_c.h"
#include "decl_Actor.h"
#include "decl_dCcAc_c.h"
#include "decl_common.h"
#include "Player.h"
#include "decl_ActorBase.h"

extern "C" {
extern int _ZTV11daWarpkun_c[];
extern void *data_020a0eac;
extern "C" int IsPlayerWarping(int a0);
extern "C" void WarpPlayer(int i, int val);
typedef int Fix12i;
extern int _ZN8dActor_c9SetRangesE5Fix12IiES1_S1_S1_(void *, Fix12i, Fix12i, Fix12i, Fix12i);
extern int _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(void *, void *, Fix12i, Fix12i, unsigned int, unsigned int);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- daWarpkun_c_Spawn, 0x020ec534, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol daWarpkun_c_Spawn
/* recovered: vtable identified, declarations from a shared header */
/* recovered: vtable identified */
/* vtable identified: VT0 = _ZTV11daWarpkun_c */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *daWarpkun_c_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(264);
    if (p) {
        _ZN8dActor_cC2Ev(p);
        p[0] = (int)(_ZTV11daWarpkun_c + 2);
        _ZN7dCcAc_cC1Ev((char *)p + 0xd4);
    }
    return p;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN11daWarpkun_c13InitResourcesEv, 0x020ec4c4, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_c13InitResourcesEv
// recovered name: daWarpkun_c_InitResources
/* recovered: renamed to Class_Method */
/* daWarpkun_c::InitResources - recovered from vtable slot identity */
s32 daWarpkun_c::InitResources() {
    void * c = (void *)this;
  int v = *((int *) (((char *) c) + 8));
  int r = (((*((int *) (((char *) c) + 8))) & 0xf) + 1) << 0x12;
  _ZN8dActor_c9SetRangesE5Fix12IiES1_S1_S1_(c, 0, r, r + 0x7d0000, 0);
  _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(((char *) c) + 0xd4, c, r, ((((v & 0xFFFFFFFFu) >> 4) & 0xf) + 1) << 0x12, 2, 0x400000);
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN11daWarpkun_c8BehaviorEv, 0x020ec410, size 0xb4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_c8BehaviorEv
// recovered name: daWarpkun_c::Behavior
/* daWarpkun_c::Behavior - vtable slot 6, overriding fBase_c::Behavior(). Migrated
 * to a real member: `c + 0xf8` is mdCcAc_c.otherOwner
 * (include/dCc_c.h, 0x24 into the embedded dCcAc_c at
 * 0xd4 -- 0xd4 + 0x24 = 0xf8) and `c + 0xd4` casts to that same member's
 * base for Clear()/Update(); `c + 0x8e` and `c + 8` are dActor_c's own
 * mAngleY and param1, already recovered in dActor_c.h (mAngleY is
 * repurposed here as a warp-in-progress flag, not an angle). The found
 * actor's own fields (actorID 0x00c, mPlayerNo 0x6d8) are real Player
 * members once cast. */
s32 daWarpkun_c::Behavior()
{
    unsigned int id = mdCcAc_c.otherOwner;
    if (id != 0) {
        if (mAngleY == 0) {
            dActor_c *a = dActor_c::FindWithID(id);
            if (a != 0) {
                int isPlayer = (a->actorID == 0xbf) ? 1 : 0;
                if (isPlayer != 0) {
                    Player *p = (Player *)a;
                    if (IsPlayerWarping(p->mPlayerNo) != 0) {
                        mAngleY = 1;
                    } else if (p->CanWarp()) {
                        unsigned int param = (param1 >> 0xc) + 1;
                        WarpPlayer(p->mPlayerNo, param & 0xff);
                    }
                }
            }
        }
    } else {
        mAngleY = 0;
    }

    mdCcAc_c.Clear();
    mdCcAc_c.Update();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN11daWarpkun_c6RenderEv, 0x020ec408, size 0x8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_c6RenderEv
// recovered name: daWarpkun_c_Render
/* recovered: renamed to Class_Method */
/* daWarpkun_c::Render - recovered from vtable slot identity */
s32 daWarpkun_c::Render() {
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN11daWarpkun_c16OnPendingDestroyEv, 0x020ec404, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_c16OnPendingDestroyEv
// recovered name: daWarpkun_c_OnPendingDestroy
/* recovered: renamed to Class_Method */
/* daWarpkun_c::OnPendingDestroy - recovered from vtable slot identity */
void daWarpkun_c::OnPendingDestroy() {
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN11daWarpkun_c16CleanupResourcesEv, 0x020ec3fc, size 0x8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_c16CleanupResourcesEv
// recovered name: daWarpkun_c_CleanupResources
/* recovered: renamed to Class_Method */
/* daWarpkun_c::CleanupResources - recovered from vtable slot identity */
s32 daWarpkun_c::CleanupResources() {
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN11daWarpkun_cD0Ev, 0x020ec3b8, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_cD0Ev
/* The DELETING DESTRUCTOR, vtable slot 17. Deleted: keeping this hand-written
   mangled-name free-function body next to the real out-of-line daWarpkun_c::~daWarpkun_c()
   (D1, below) is the mwcc ICE this series has hit repeatedly (ELFgen.c:483).
   The real D1 makes the compiler synthesize D0 itself, byte-identical to the
   ROM (confirmed by verify, not assumed). */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN11daWarpkun_cD1Ev, 0x020ec388, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daWarpkun_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body.
 * Vtable slot 16: one vtable store, the members in reverse, then ~dActor_c. */
daWarpkun_c::~daWarpkun_c()
{
}
