/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_ENEMY_H
#define DECL_ENEMY_H
#include "common.h"


#ifdef __cplusplus
/* These declare ROM functions by the mangled name the ROM already uses. Compiled as
 * C++ without this, the compiler mangles those names a SECOND time and emits
 * references like _Z28_ZN13SharedFilePtr7ReleaseEvPv, which nothing defines -- the
 * file still matches, but it can never be enrolled into the ROM build. */
extern "C" {
#endif

extern int _ZN5Enemy27SpawnParticlesIfHitOtherObjER12CylinderClsn(void*, void*);
extern void _ZN5Enemy20KillByInvincibleCharERK10Vector3_16R6Player(void*, Vector3_16*, void*, int);
extern void _ZN5Enemy22SpawnMegaCharParticlesER5ActorPc(void*, void*, char*);
extern void _ZN5EnemyC2Ev(void*);

#ifdef __cplusplus
}
#endif

#endif
