/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_NESTEDHEAPITERATOR_H
#define DECL_NESTEDHEAPITERATOR_H
#include "common.h"


#ifdef __cplusplus
/* These declare ROM functions by the mangled name the ROM already uses. Compiled as
 * C++ without this, the compiler mangles those names a SECOND time and emits
 * references like _Z28_ZN13SharedFilePtr7ReleaseEvPv, which nothing defines -- the
 * file still matches, but it can never be enrolled into the ROM build. */
extern "C" {
#endif

extern void _ZN18NestedHeapIterator4InitEP13HeapAllocator(char*, char*);
extern void _ZN18NestedHeapIterator8AddFirstEP13HeapAllocator(char*, char*);
extern void _ZN18NestedHeapIteratorC1Ej(void*, u32);
extern void*_ZN18NestedHeapIterator4NextEP13HeapAllocator(void*, void*);

#ifdef __cplusplus
}
#endif

#endif
