/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_EXTENDINGMESHCOLLIDER_H
#define DECL_EXTENDINGMESHCOLLIDER_H
#include "common.h"


#ifdef __cplusplus
/* These declare ROM functions by the mangled name the ROM already uses. Compiled as
 * C++ without this, the compiler mangles those names a SECOND time and emits
 * references like _Z28_ZN13SharedFilePtr7ReleaseEvPv, which nothing defines -- the
 * file still matches, but it can never be enrolled into the ROM build. */
extern "C" {
#endif

extern int _ZN21ExtendingMeshCollider9SetScaleYE5Fix12IiE(void*, int);
extern void _ZN21ExtendingMeshColliderC1Ev(void*);
extern void _ZN21ExtendingMeshColliderD1Ev(void*);

#ifdef __cplusplus
}
#endif

#endif
